### PR TITLE
Add conda forge badge to readme

### PR DESCRIPTION
**Pull request by mayou36**
In order to make clear that it is available on conda-forge

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Ah, I was not aware of this :D. Just doing a search now I found https://github.com/conda-forge/hepunits-feedstock. Cc'ing @chrisburr as I see no release just yet. Let's just wait for one ... Thanks for the PR anyway 👍 .

**Comment by mayou36** [comment]
I think there are, the newest one is 2.0.1 and I can also install it. Do I miss something?

**Comment by eduardo-rodrigues** [comment]
Oops, I was *far* too quick. Yes, totally.

**Comment by eduardo-rodrigues** [comment]
Thanks for the PR.

**Pull request merged**
