### PR TITLE
Better documentation in the README

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Have a look at it @henryiii and @mayou36 if you have a bit of time. Otherwise I will go ahead later and merge. Thanks.

### CODE REVIEW

**Review by henryiii — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
Thanks @henryiii. Following your MR https://github.com/scikit-hep/hepunits/pull/36: do you have something else in the pipeline or else we try the tagging and automatic deployment?

**Comment by henryiii** [comment]
I think it's ready to try.

**Comment by eduardo-rodrigues** [comment]
OK. Going to make a patch release. Thanks.

**Comment by eduardo-rodrigues** [comment]
Version 2.1.1 available in PyPI :-). For conda-forge we will have to wait a bit. All good 👍 .

**Pull request merged**
